### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by jirisykora83** [osjoberg/HtmlPerformanceKit#1]
First i want to thank you for great project / nugget package. Recently i migrate some scrapers to your solution.

But only "issue" what i have is warning when i try to reference HtmlPerformanceKit in netcoreapp2.0 project. But it seen like it work fine. But i still think it will be nice if you can migrate your project to new .NET Standard (look like your currently targeting to v4.5.2 is equal to .NET Standard 1.2).

Also it would be good if you migrate to new .csproj format (i use this https://github.com/hvanbakel/CsprojToVs2017)

**Comment by osjoberg** [comment]
Thank you for the feedback! I will update to .NET Standard and update the project files when I have time for a new release.

**Comment by osjoberg** [comment]
Now targets .NET Standard 1.0, project files are updated to new format. Be aware that the benchmark and test suite still depends on "old" .NET libraries that have not been migrated to .NET standard yet.
