### ISSUE TITLE
Accept TextReader

### ISSUE THREAD

**Issue by SebastianStehle** [osjoberg/HtmlPerformanceKit#5]
First of all: Very impressive performance. I justed tested it with my mjml lib:
https://github.com/SebastianStehle/mjml-net/issues/174

If you would make a small change. Is it possible to change the input from StreamReader to TextReader? Because I already have a string and would avoid the conversion.

**Comment by osjoberg** [comment]
Thank you for your feedback. I have added a new constructor for TextReader and pushed an updated package to nuget.

**Comment by SebastianStehle** [comment]
Thanks a lot.
